baseURL: '/'
languageCode: en-us
theme: devops-maturity
# defaultContentLanguageInSubdir: true
defaultContentLanguage: "en"

# Global parameters
params:
  license:
    title: License
    action:
      label: Creative Commons - CC BY 3.0
      url: 'https://creativecommons.org/licenses/by/3.0/'

  footer:
    logos:
    - name: github
      url: 'https://github.com/devops-maturity/specification'

# Languages parameters
languages:
  en:
    params:
      weight: 1
      languageName: "English"
      title: DevOps Maturity
      description: DevOps Maturity Specification — assess, improve, and showcase your DevOps maturity.
      actions:
      - label: Quick Summary
        url: '#summary'
      - label: Full Specification
        url: '#specification'
      - label: Contribute
        url: 'https://github.com/devops-maturity/specification'
      # versions:
      #   current: v1.0.0
  zh:
    params:
      weight: 2
      languageName: "中文"
      title: DevOps 成熟度
      description: DevOps 成熟度规范 - 评估、改进和展示你的 DevOps 成熟度。
      actions:
      - label: 概述
        url: '#概述'
      - label: 完整规范
        url: '#规范'
      - label: 贡献
        url: 'https://github.com/devops-maturity/specification'
