name = "Conventional Branch"
license = "MIT"
description = "Hugo theme for Conventional Branch website"
homepage = "https://github.com/devops-maturity/devops-maturity"
tags = []
features = []
min_version = "0.42"
