name = "DevOps Maturity"
license = "MIT"
description = "Hugo theme for DevOps Maturity website"
homepage = "https://github.com/devops-maturity/devops-maturity"
tags = []
features = []
min_version = "0.42"
